# Generated by Django 5.1.5 on 2025-01-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_app', '0002_customer_last_login_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='code',
            new_name='customer_code',
        ),
    ]
