"""
Django settings for customer_order project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ys$$2m3zv@5d)5&q920y9qo@9@ym90#s_(jq9df-l@(eczd9o%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'customer_order_app.Customer'


# If you're using credentials like cookies or HTTP authentication, enable this
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'customer_order_app',
     'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid',
    'oidc_provider',
]
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    'allauth.account.auth_backends.AuthenticationBackend',

]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',

    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'mozilla_django_oidc.middleware.SessionRefresh',

]

ROOT_URLCONF = 'customer_order.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'customer_order.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SOCIALACCOUNT_PROVIDERS = {
    'openid': {
        'SCOPE': [
            'openid',
            'email',
            'profile',
        ],
        'AUTH_PARAMS': {
            'response_type': 'code',
        },
        'OAUTH2_PARAMS': {
            'client_id': '302335069573-pjd95ekmam8ap8fkr2hc0lij3a1hgfn7.apps.googleusercontent.com',
            'client_secret': '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',
            'redirect_uri': 'http://localhost:7000/accounts/openid/login/callback/',
        },
        'EXCHANGE_TOKEN_URL': 'https://oauth2.googleapis.com/token',
        'AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/auth',
        'USERINFO_URL': 'https://www.googleapis.com/oauth2/v3/userinfo',
    }
}
LOGIN_REDIRECT_URL = '/customers/'  # Redirect to the home page after login
LOGOUT_REDIRECT_URL = '/'  # Redirect to the home page after logout

#
# OIDC Configuration
OIDC_RP_CLIENT_ID = 'fBw2P27uLpXEl5jzOrGGxEFAiKEDHDI0'
OIDC_RP_CLIENT_SECRET = '-KipgUYXPW58mn5X300IJS6KeX6-uwutD1zoZUEA0jAi9Vum6pyQZmV1l1iUsaWR'
OIDC_OP_AUTHORIZATION_ENDPOINT = 'https://dev-2e8u3lymvt420516.us.auth0.com/authorize'
OIDC_OP_TOKEN_ENDPOINT = 'https://dev-2e8u3lymvt420516.us.auth0.com/token'
# OIDC_OP_USERINFO_ENDPOINT = 'https://dev-2e8u3lymvt420516.us.auth0.com/userinfo'
OIDC_OP_USER_ENDPOINT = 'https://dev-2e8u3lymvt420516.us.auth0.com/userinfo'
OIDC_OP_JWKS_ENDPOINT = 'https://dev-2e8u3lymvt420516.us.auth0.com/.well-known/jwks.json'
# Additional recommended settings
OIDC_AUTHENTICATE_CLASS = 'mozilla_django_oidc.views.OIDCAuthenticationRequestView'
OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_RP_SCOPES = 'openid email profile'
OIDC_TOKEN_REFRESH_RATE = 60 * 60  # Refresh token every hour
OIDC_STORE_ACCESS_TOKEN = True
AUTH0_AUDIENCE = 'https://dev-2e8u3lymvt420516.us.auth0.com/api/v2/'

OIDC_DRF_AUTH_BACKEND = 'mozilla_django_oidc.auth.OIDCAuthenticationBackend'
