name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Railway CLI
      run: |
        npm install -g @railway/cli

    - name: Check Railway status
      run: |
       railway status
    - name: Install Railway CLI
      run: |
       npm install -g @railway/cli@latest
    - name: Check for requirements.txt
      run: |
        ls -la
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway login --token $RAILWAY_TOKEN
        railway up --detach
    - name: Run migrations
      run: |
        railway run python manage.py migrate