name: Django CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: postgres://django:django@localhost:5432/test_db
        run: |
          python manage.py migrate
      - name: start project
        env:
          DATABASE_URL: postgres://django:django@localhost:5432/test_db

        run: |
          python manage.py runserver

      - name: Run tests
        env:
          DATABASE_URL: postgres://django:django@localhost:5432/test_db
        run: |
          python manage.py test
