name: Django CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
                - name: Verify Docker login
                run: docker info

        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t lumbs/customer_order_app:latest .
          docker push lumbs/customer_order_app:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull lumbs/customer_order_app:latest
            docker stop customer_order_app || true
            docker rm customer_order_app || true
            docker run -d -p 8000:8000 --name customer_order_app lumbs/customer_order_app:latest
